$ ->
	Utils.Actions.batch_action("#destroy_alarms",".alarm_checkbox")
	Utils.Actions.batch_action("#destroy_regions",".region_checkbox")
	Utils.Actions.batch_action("#destroy_alarms",".alarm_checkbox")
	Utils.Actions.batch_action("#destroy_car_manufacturers",".car_manufacturer_checkbox")
	Utils.Actions.batch_action("#destroy_car_models",".car_model_checkbox")
	Utils.Actions.batch_action("#destroy_car_types",".car_type_checkbox")
	Utils.Actions.batch_action("#destroy_cars",".car_checkbox")
	Utils.Actions.batch_action("#destroy_groups",".group_checkbox")
	Utils.Actions.batch_action("#destroy_device_manufacturers",".device_manufacturer_checkbox")
	Utils.Actions.batch_action("#destroy_device_models",".device_model_checkbox")
	Utils.Actions.batch_action("#batch_destroy",".device_type_checkbox")
	Utils.Actions.batch_action("#batch_destroy",".device_type_checkbox")
	Utils.Actions.batch_action("#destroy_simcards",".simcard_checkbox")
	Utils.Actions.batch_action("#destroy_work_schedule_groups",".work_schedule_group_checkbox")
	Utils.Actions.batch_action("#destroy_work_schedules",".work_schedule_checkbox")