development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://trackman-faye.herokuapp.com/faye"
  secret_token: "trackman"
  signature_expiration: 3600 # one hour
