# Sidekiq Configuration
---
development:
  :logfile: ./log/sidekiq_development.log
  :verbose: true
  :pidfile: ./tmp/pids/sidekiq.pid
  :concurrency: 10
  :queues:
    - [mailer, 10]
    - [default, 10]
    - [traccar, 10]

production:
  :logfile: ./log/sidekiq_production.log
  :verbose: true
  :concurrency: 10
  :queues:
    - [mailer, 10]
    - [default, 10]
    - [traccar, 10]