require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeviceManufacturersController do

  # This should return the minimal set of attributes required to create a valid
  # DeviceManufacturer. As you add validations to DeviceManufacturer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeviceManufacturersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all device_manufacturers as @device_manufacturers" do
      device_manufacturer = DeviceManufacturer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:device_manufacturers).should eq([device_manufacturer])
    end
  end

  describe "GET show" do
    it "assigns the requested device_manufacturer as @device_manufacturer" do
      device_manufacturer = DeviceManufacturer.create! valid_attributes
      get :show, {:id => device_manufacturer.to_param}, valid_session
      assigns(:device_manufacturer).should eq(device_manufacturer)
    end
  end

  describe "GET new" do
    it "assigns a new device_manufacturer as @device_manufacturer" do
      get :new, {}, valid_session
      assigns(:device_manufacturer).should be_a_new(DeviceManufacturer)
    end
  end

  describe "GET edit" do
    it "assigns the requested device_manufacturer as @device_manufacturer" do
      device_manufacturer = DeviceManufacturer.create! valid_attributes
      get :edit, {:id => device_manufacturer.to_param}, valid_session
      assigns(:device_manufacturer).should eq(device_manufacturer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeviceManufacturer" do
        expect {
          post :create, {:device_manufacturer => valid_attributes}, valid_session
        }.to change(DeviceManufacturer, :count).by(1)
      end

      it "assigns a newly created device_manufacturer as @device_manufacturer" do
        post :create, {:device_manufacturer => valid_attributes}, valid_session
        assigns(:device_manufacturer).should be_a(DeviceManufacturer)
        assigns(:device_manufacturer).should be_persisted
      end

      it "redirects to the created device_manufacturer" do
        post :create, {:device_manufacturer => valid_attributes}, valid_session
        response.should redirect_to(DeviceManufacturer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved device_manufacturer as @device_manufacturer" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceManufacturer.any_instance.stub(:save).and_return(false)
        post :create, {:device_manufacturer => { "name" => "invalid value" }}, valid_session
        assigns(:device_manufacturer).should be_a_new(DeviceManufacturer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceManufacturer.any_instance.stub(:save).and_return(false)
        post :create, {:device_manufacturer => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested device_manufacturer" do
        device_manufacturer = DeviceManufacturer.create! valid_attributes
        # Assuming there are no other device_manufacturers in the database, this
        # specifies that the DeviceManufacturer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeviceManufacturer.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => device_manufacturer.to_param, :device_manufacturer => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested device_manufacturer as @device_manufacturer" do
        device_manufacturer = DeviceManufacturer.create! valid_attributes
        put :update, {:id => device_manufacturer.to_param, :device_manufacturer => valid_attributes}, valid_session
        assigns(:device_manufacturer).should eq(device_manufacturer)
      end

      it "redirects to the device_manufacturer" do
        device_manufacturer = DeviceManufacturer.create! valid_attributes
        put :update, {:id => device_manufacturer.to_param, :device_manufacturer => valid_attributes}, valid_session
        response.should redirect_to(device_manufacturer)
      end
    end

    describe "with invalid params" do
      it "assigns the device_manufacturer as @device_manufacturer" do
        device_manufacturer = DeviceManufacturer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceManufacturer.any_instance.stub(:save).and_return(false)
        put :update, {:id => device_manufacturer.to_param, :device_manufacturer => { "name" => "invalid value" }}, valid_session
        assigns(:device_manufacturer).should eq(device_manufacturer)
      end

      it "re-renders the 'edit' template" do
        device_manufacturer = DeviceManufacturer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceManufacturer.any_instance.stub(:save).and_return(false)
        put :update, {:id => device_manufacturer.to_param, :device_manufacturer => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested device_manufacturer" do
      device_manufacturer = DeviceManufacturer.create! valid_attributes
      expect {
        delete :destroy, {:id => device_manufacturer.to_param}, valid_session
      }.to change(DeviceManufacturer, :count).by(-1)
    end

    it "redirects to the device_manufacturers list" do
      device_manufacturer = DeviceManufacturer.create! valid_attributes
      delete :destroy, {:id => device_manufacturer.to_param}, valid_session
      response.should redirect_to(device_manufacturers_url)
    end
  end

end
