require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeviceModelsController do

  # This should return the minimal set of attributes required to create a valid
  # DeviceModel. As you add validations to DeviceModel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeviceModelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all device_models as @device_models" do
      device_model = DeviceModel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:device_models).should eq([device_model])
    end
  end

  describe "GET show" do
    it "assigns the requested device_model as @device_model" do
      device_model = DeviceModel.create! valid_attributes
      get :show, {:id => device_model.to_param}, valid_session
      assigns(:device_model).should eq(device_model)
    end
  end

  describe "GET new" do
    it "assigns a new device_model as @device_model" do
      get :new, {}, valid_session
      assigns(:device_model).should be_a_new(DeviceModel)
    end
  end

  describe "GET edit" do
    it "assigns the requested device_model as @device_model" do
      device_model = DeviceModel.create! valid_attributes
      get :edit, {:id => device_model.to_param}, valid_session
      assigns(:device_model).should eq(device_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeviceModel" do
        expect {
          post :create, {:device_model => valid_attributes}, valid_session
        }.to change(DeviceModel, :count).by(1)
      end

      it "assigns a newly created device_model as @device_model" do
        post :create, {:device_model => valid_attributes}, valid_session
        assigns(:device_model).should be_a(DeviceModel)
        assigns(:device_model).should be_persisted
      end

      it "redirects to the created device_model" do
        post :create, {:device_model => valid_attributes}, valid_session
        response.should redirect_to(DeviceModel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved device_model as @device_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceModel.any_instance.stub(:save).and_return(false)
        post :create, {:device_model => { "name" => "invalid value" }}, valid_session
        assigns(:device_model).should be_a_new(DeviceModel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceModel.any_instance.stub(:save).and_return(false)
        post :create, {:device_model => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested device_model" do
        device_model = DeviceModel.create! valid_attributes
        # Assuming there are no other device_models in the database, this
        # specifies that the DeviceModel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeviceModel.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => device_model.to_param, :device_model => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested device_model as @device_model" do
        device_model = DeviceModel.create! valid_attributes
        put :update, {:id => device_model.to_param, :device_model => valid_attributes}, valid_session
        assigns(:device_model).should eq(device_model)
      end

      it "redirects to the device_model" do
        device_model = DeviceModel.create! valid_attributes
        put :update, {:id => device_model.to_param, :device_model => valid_attributes}, valid_session
        response.should redirect_to(device_model)
      end
    end

    describe "with invalid params" do
      it "assigns the device_model as @device_model" do
        device_model = DeviceModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => device_model.to_param, :device_model => { "name" => "invalid value" }}, valid_session
        assigns(:device_model).should eq(device_model)
      end

      it "re-renders the 'edit' template" do
        device_model = DeviceModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeviceModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => device_model.to_param, :device_model => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested device_model" do
      device_model = DeviceModel.create! valid_attributes
      expect {
        delete :destroy, {:id => device_model.to_param}, valid_session
      }.to change(DeviceModel, :count).by(-1)
    end

    it "redirects to the device_models list" do
      device_model = DeviceModel.create! valid_attributes
      delete :destroy, {:id => device_model.to_param}, valid_session
      response.should redirect_to(device_models_url)
    end
  end

end
