require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeleprovidersController do

  # This should return the minimal set of attributes required to create a valid
  # Teleprovider. As you add validations to Teleprovider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeleprovidersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all teleproviders as @teleproviders" do
      teleprovider = Teleprovider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teleproviders).should eq([teleprovider])
    end
  end

  describe "GET show" do
    it "assigns the requested teleprovider as @teleprovider" do
      teleprovider = Teleprovider.create! valid_attributes
      get :show, {:id => teleprovider.to_param}, valid_session
      assigns(:teleprovider).should eq(teleprovider)
    end
  end

  describe "GET new" do
    it "assigns a new teleprovider as @teleprovider" do
      get :new, {}, valid_session
      assigns(:teleprovider).should be_a_new(Teleprovider)
    end
  end

  describe "GET edit" do
    it "assigns the requested teleprovider as @teleprovider" do
      teleprovider = Teleprovider.create! valid_attributes
      get :edit, {:id => teleprovider.to_param}, valid_session
      assigns(:teleprovider).should eq(teleprovider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Teleprovider" do
        expect {
          post :create, {:teleprovider => valid_attributes}, valid_session
        }.to change(Teleprovider, :count).by(1)
      end

      it "assigns a newly created teleprovider as @teleprovider" do
        post :create, {:teleprovider => valid_attributes}, valid_session
        assigns(:teleprovider).should be_a(Teleprovider)
        assigns(:teleprovider).should be_persisted
      end

      it "redirects to the created teleprovider" do
        post :create, {:teleprovider => valid_attributes}, valid_session
        response.should redirect_to(Teleprovider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teleprovider as @teleprovider" do
        # Trigger the behavior that occurs when invalid params are submitted
        Teleprovider.any_instance.stub(:save).and_return(false)
        post :create, {:teleprovider => { "name" => "invalid value" }}, valid_session
        assigns(:teleprovider).should be_a_new(Teleprovider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Teleprovider.any_instance.stub(:save).and_return(false)
        post :create, {:teleprovider => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teleprovider" do
        teleprovider = Teleprovider.create! valid_attributes
        # Assuming there are no other teleproviders in the database, this
        # specifies that the Teleprovider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Teleprovider.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => teleprovider.to_param, :teleprovider => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested teleprovider as @teleprovider" do
        teleprovider = Teleprovider.create! valid_attributes
        put :update, {:id => teleprovider.to_param, :teleprovider => valid_attributes}, valid_session
        assigns(:teleprovider).should eq(teleprovider)
      end

      it "redirects to the teleprovider" do
        teleprovider = Teleprovider.create! valid_attributes
        put :update, {:id => teleprovider.to_param, :teleprovider => valid_attributes}, valid_session
        response.should redirect_to(teleprovider)
      end
    end

    describe "with invalid params" do
      it "assigns the teleprovider as @teleprovider" do
        teleprovider = Teleprovider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Teleprovider.any_instance.stub(:save).and_return(false)
        put :update, {:id => teleprovider.to_param, :teleprovider => { "name" => "invalid value" }}, valid_session
        assigns(:teleprovider).should eq(teleprovider)
      end

      it "re-renders the 'edit' template" do
        teleprovider = Teleprovider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Teleprovider.any_instance.stub(:save).and_return(false)
        put :update, {:id => teleprovider.to_param, :teleprovider => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teleprovider" do
      teleprovider = Teleprovider.create! valid_attributes
      expect {
        delete :destroy, {:id => teleprovider.to_param}, valid_session
      }.to change(Teleprovider, :count).by(-1)
    end

    it "redirects to the teleproviders list" do
      teleprovider = Teleprovider.create! valid_attributes
      delete :destroy, {:id => teleprovider.to_param}, valid_session
      response.should redirect_to(teleproviders_url)
    end
  end

end
