require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkSchedulesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkSchedule. As you add validations to WorkSchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "car_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkSchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all work_schedules as @work_schedules" do
      work_schedule = WorkSchedule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:work_schedules).should eq([work_schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested work_schedule as @work_schedule" do
      work_schedule = WorkSchedule.create! valid_attributes
      get :show, {:id => work_schedule.to_param}, valid_session
      assigns(:work_schedule).should eq(work_schedule)
    end
  end

  describe "GET new" do
    it "assigns a new work_schedule as @work_schedule" do
      get :new, {}, valid_session
      assigns(:work_schedule).should be_a_new(WorkSchedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested work_schedule as @work_schedule" do
      work_schedule = WorkSchedule.create! valid_attributes
      get :edit, {:id => work_schedule.to_param}, valid_session
      assigns(:work_schedule).should eq(work_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkSchedule" do
        expect {
          post :create, {:work_schedule => valid_attributes}, valid_session
        }.to change(WorkSchedule, :count).by(1)
      end

      it "assigns a newly created work_schedule as @work_schedule" do
        post :create, {:work_schedule => valid_attributes}, valid_session
        assigns(:work_schedule).should be_a(WorkSchedule)
        assigns(:work_schedule).should be_persisted
      end

      it "redirects to the created work_schedule" do
        post :create, {:work_schedule => valid_attributes}, valid_session
        response.should redirect_to(WorkSchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved work_schedule as @work_schedule" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkSchedule.any_instance.stub(:save).and_return(false)
        post :create, {:work_schedule => { "car_id" => "invalid value" }}, valid_session
        assigns(:work_schedule).should be_a_new(WorkSchedule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkSchedule.any_instance.stub(:save).and_return(false)
        post :create, {:work_schedule => { "car_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested work_schedule" do
        work_schedule = WorkSchedule.create! valid_attributes
        # Assuming there are no other work_schedules in the database, this
        # specifies that the WorkSchedule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkSchedule.any_instance.should_receive(:update).with({ "car_id" => "1" })
        put :update, {:id => work_schedule.to_param, :work_schedule => { "car_id" => "1" }}, valid_session
      end

      it "assigns the requested work_schedule as @work_schedule" do
        work_schedule = WorkSchedule.create! valid_attributes
        put :update, {:id => work_schedule.to_param, :work_schedule => valid_attributes}, valid_session
        assigns(:work_schedule).should eq(work_schedule)
      end

      it "redirects to the work_schedule" do
        work_schedule = WorkSchedule.create! valid_attributes
        put :update, {:id => work_schedule.to_param, :work_schedule => valid_attributes}, valid_session
        response.should redirect_to(work_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the work_schedule as @work_schedule" do
        work_schedule = WorkSchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkSchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => work_schedule.to_param, :work_schedule => { "car_id" => "invalid value" }}, valid_session
        assigns(:work_schedule).should eq(work_schedule)
      end

      it "re-renders the 'edit' template" do
        work_schedule = WorkSchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkSchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => work_schedule.to_param, :work_schedule => { "car_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested work_schedule" do
      work_schedule = WorkSchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => work_schedule.to_param}, valid_session
      }.to change(WorkSchedule, :count).by(-1)
    end

    it "redirects to the work_schedules list" do
      work_schedule = WorkSchedule.create! valid_attributes
      delete :destroy, {:id => work_schedule.to_param}, valid_session
      response.should redirect_to(work_schedules_url)
    end
  end

end
